### ISSUE TITLE
Download?

### ISSUE THREAD

**Issue by mzaini30** [anasrar/Jekyll-Post-Generator#1]
Output Markdownnya nggak bisa didownload Bang.

**Comment by anasrar** [comment]
input date harus di isi

**Comment by mzaini30** [comment]
Owalah. Thanks yo 😂

Zen - 081545143654
Pada tanggal 7 Jul 2019 09.34, "Anas RAR" <notifications@github.com>
menulis:

**Comment by mzaini30** [comment]
Thanks 🙋

Zen - Seorang developer website asal Samarinda. Untuk melihat rekam
jejaknya, bisa mampir ke https://blogzen.herokuapp.com 🙋
Pada tanggal 7 Jul 2019 09.52, "Zen Zen" <muhzaini30@gmail.com> menulis:

**Comment by anasrar** [comment]
lupa buat ngefix nya, lagi fokus projek lain
ntar di fixnya

**Comment by mzaini30** [comment]
Okay. Thanks banget lah udah buat tools yang berguna 🙋

Zen - Seorang developer website asal Samarinda. Untuk melihat rekam
jejaknya, bisa mampir ke https://blogzen.herokuapp.com 🙋
Pada tanggal 7 Jul 2019 12.57, "Anas RAR" <notifications@github.com>
menulis:
